name: Collect logs using juju-k8s-crashdump
description: Use-juju-k8s-crashdump to collect logs

inputs:
  kubeconf:
    description: "Path to a kubeconf"
    required: true
  controller:
    description: "Name of a controller to collect logs for"
    required: true
  output_path:
    description: "Path to write the crashdump to, will write it as a .tar.gz file"
    retquired: true
  proxy:
    description: "url for the a proxy to connect to pip with"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  - name: Clone repo
    uses: actions/checkout@v4
    with:
      repository: canonical/juju-k8s-crashdump
      ref: use-output-path
      path: ./juju-k8s-crashdump
  - name: install pipx
    shell: bash
    working-directory: ./juju-k8s-crashdump
    run: |
      sudo apt-get update --quiet
      sudo apt-get install pipx --quiet --assume-yes
  - name: Setup pip proxy
    if: ${{inputs.proxy}} != ""
    shell: bash
    working-directory: ./juju-k8s-crashdump
    run: |
      sudo tee /etc/pip.conf <<EOF
      [global]
      proxy=${{inputs.proxy}}
      EOF
  - name: Install
    shell: bash
    working-directory: ./juju-k8s-crashdump
    run: |
      sudo snap install kubectl --classic
      pipx install poetry==1.6
      pipx install .
  - name: Collect Logs
    shell: bash
    working-directory: ./juju-k8s-crashdump
    run: |
      juju-k8s-crashdump ${{ inputs.kubeconf }} ${{ inputs.controller }} --output ${{ inputs.output_path }}
