name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install poetry
        run: pipx install poetry==1.6

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: ./scripts/lint.sh
